### ISSUE TITLE
Makefile race condition

### ISSUE THREAD

**Issue by coderobe** [wacossusca34/glava#8]
When invoked with multiple jobs (`make -jX`) the `glava` rule may run before `glad` finished, breaking because the header(s) haven't been generated.

**Comment by coderobe** [comment]
This is a show-stopper for a proper Archlinux PKGBUILD, unless the PKGBUILD implements a workaround (see https://github.com/coderobe/pkgbuilds/blob/master/glava-git/PKGBUILD#L36)

There are some other issues with the Makefile like it not respecting common variables as `make install` path prefix, forcing me to re-write the install routine in the PKGBUILD, which is not perfect

**Comment by wacossusca34** [comment]
Should be fixed now, you can use `DESTDIR` for a path prefix for a PKGBUILD when using `make install`.

**Comment by coderobe** [comment]
Unfortunately the commit doesn't seem to fix the race condition at all.
Screenshots:  
Single-threaded
![2018-01-18 020401 iridium](https://user-images.githubusercontent.com/8442384/35075581-30a45560-fbf4-11e7-958c-df01d5649e24.png)

Multi-threaded
![2018-01-18 020434 iridium](https://user-images.githubusercontent.com/8442384/35075593-440f73aa-fbf4-11e7-971f-c30025cbf912.png)

**Comment by coderobe** [comment]
Also, DESTDIR does not work correctly because the Makefile is currently not attempting to create the path leading up to it if it doesn't exist [here](https://github.com/wacossusca34/glava/blob/f767ae0b6cd4cc5b33c4c760f805a8694aa62644/Makefile#L77)

I recommend using `install`(1), possibly like this:
```Makefile
install -Dm755 glava "$(DESTDIR)/usr/bin/glava"
install -d "$(DESTDIR)/$(SHADER_DIR)"
cp -rv shaders/* "$(DESTDIR)/$(SHADER_DIR)"
```
